# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'control_tab.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(569, 861)
        self.leSetCustomTemp = QtWidgets.QLineEdit(Form)
        self.leSetCustomTemp.setGeometry(QtCore.QRect(190, 220, 113, 20))
        self.leSetCustomTemp.setObjectName("leSetCustomTemp")
        self.btn200K = QtWidgets.QPushButton(Form)
        self.btn200K.setGeometry(QtCore.QRect(80, 150, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn200K.setFont(font)
        self.btn200K.setCheckable(True)
        self.btn200K.setObjectName("btn200K")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(20, 10, 81, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.btn500K = QtWidgets.QPushButton(Form)
        self.btn500K.setGeometry(QtCore.QRect(180, 80, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn500K.setFont(font)
        self.btn500K.setCheckable(True)
        self.btn500K.setObjectName("btn500K")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(110, 260, 91, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.scrollArea = QtWidgets.QScrollArea(Form)
        self.scrollArea.setGeometry(QtCore.QRect(10, 300, 551, 531))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 549, 529))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(20, 218, 161, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.btnSetCustomTemp = QtWidgets.QPushButton(Form)
        self.btnSetCustomTemp.setGeometry(QtCore.QRect(310, 218, 75, 23))
        self.btnSetCustomTemp.setObjectName("btnSetCustomTemp")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(30, 260, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(20, 90, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.cbSerial = QtWidgets.QComboBox(Form)
        self.cbSerial.setGeometry(QtCore.QRect(200, 10, 241, 22))
        self.cbSerial.setObjectName("cbSerial")
        self.btn100K = QtWidgets.QPushButton(Form)
        self.btn100K.setGeometry(QtCore.QRect(180, 150, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn100K.setFont(font)
        self.btn100K.setCheckable(True)
        self.btn100K.setObjectName("btn100K")
        self.btn400K = QtWidgets.QPushButton(Form)
        self.btn400K.setGeometry(QtCore.QRect(80, 80, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn400K.setFont(font)
        self.btn400K.setCheckable(True)
        self.btn400K.setObjectName("btn400K")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(20, 160, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.btn600K = QtWidgets.QPushButton(Form)
        self.btn600K.setGeometry(QtCore.QRect(280, 80, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn600K.setFont(font)
        self.btn600K.setCheckable(True)
        self.btn600K.setObjectName("btn600K")
        self.btn700K = QtWidgets.QPushButton(Form)
        self.btn700K.setGeometry(QtCore.QRect(380, 80, 91, 41))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.btn700K.setFont(font)
        self.btn700K.setCheckable(True)
        self.btn700K.setObjectName("btn700K")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(340, 260, 201, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.btnSerialConnect = QtWidgets.QPushButton(Form)
        self.btnSerialConnect.setGeometry(QtCore.QRect(450, 10, 75, 23))
        self.btnSerialConnect.setObjectName("btnSerialConnect")
        self.line_2 = QtWidgets.QFrame(Form)
        self.line_2.setGeometry(QtCore.QRect(20, 40, 541, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.line = QtWidgets.QFrame(Form)
        self.line.setGeometry(QtCore.QRect(20, 250, 541, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.btnRefreshPorts = QtWidgets.QPushButton(Form)
        self.btnRefreshPorts.setGeometry(QtCore.QRect(110, 10, 75, 23))
        self.btnRefreshPorts.setObjectName("btnRefreshPorts")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(220, 260, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.connectLED = LEDWidget(Form)
        self.connectLED.setGeometry(QtCore.QRect(530, 11, 21, 21))
        self.connectLED.setObjectName("connectLED")
        self.monitorLED = LEDWidget(Form)
        self.monitorLED.setGeometry(QtCore.QRect(550, 270, 21, 21))
        self.monitorLED.setObjectName("monitorLED")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.btn200K.setText(_translate("Form", "200 K"))
        self.label_11.setText(_translate("Form", "Serial Port:"))
        self.btn500K.setText(_translate("Form", "500 K"))
        self.label_3.setText(_translate("Form", "Setpoint (K)"))
        self.label_14.setText(_translate("Form", "Custom Temperature:"))
        self.btnSetCustomTemp.setText(_translate("Form", "Set All"))
        self.label_5.setText(_translate("Form", "Mode"))
        self.label_12.setText(_translate("Form", "Heat:"))
        self.btn100K.setText(_translate("Form", "100 K"))
        self.btn400K.setText(_translate("Form", "400 K"))
        self.label_13.setText(_translate("Form", "Cool:"))
        self.btn600K.setText(_translate("Form", "600 K"))
        self.btn700K.setText(_translate("Form", "700 K"))
        self.label_4.setText(_translate("Form", "Change Setpoint"))
        self.btnSerialConnect.setText(_translate("Form", "Connect"))
        self.btnRefreshPorts.setText(_translate("Form", "Refresh"))
        self.label_2.setText(_translate("Form", "Current T (K)"))
from led import LEDWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
